name: assemblyscript
version: git
summary: A TypeScript-like language for WebAssembly.
description: |
  AssemblyScript compiles a variant of TypeScript to WebAssembly using Binaryen.

  See the AssemblyScript website for documentation:
  https://www.assemblyscript.org
icon: media/icon.svg
grade: stable
confinement: strict
apps:
  asc:
    command: asc
parts:
  assemblyscript:
    source: .
    plugin: nodejs
