name: assemblyscript
version: git
summary: A TypeScript to WebAssembly compiler.
description: AssemblyScript compiles strictly typed TypeScript to WebAssembly.
grade: devel
confinement: strict
apps:
  asc:
    command: asc
parts:
  assemblyscript:
    source: .
    plugin: nodejs
